server:
  port: 9010

spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      authorizationserver:
        client:
          shinnybest:
            registration:
              client-id: shinnybest
              client-secret: $2a$10$KF.nQbtbNFAAgVgBShSCge8kMtSsNk0RT5AsfVGD/saaF4FIiCQ/i
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:8094/login/oauth2/code/shinnybest
              post-logout-redirect-uris:
                - http://localhost:8094/
              scopes:
                - openid
                - profile
                - email
            require-authorization-consent: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
